---
title: "Introduction to R"
---

# Introduction

This site contains the materials for an R course.

# Description

**R** is one of the leading programming languages in **Data Science** for
interacting with, analyzing and visualizing data.

In this training course, we aim to provide a friendly introduction to R pitched
at a beginners level but also for those who have been on R training courses
previously and would like a refresher or to consolidate their skills.

# Sections

0. [Getting set up](week0.html) - installing R and RStudio

1. [Introduction to R](week1.html) - Interacting with R using RStudio and
introducing objects, data types and functions

2. [Working with data](week2.html) - Creating R scripts, working with tabular
data and other types of objects in R, reading data into R

3. [Data visualization with ggplot2](week3.html) - A common grammar to create
scatter plots, bar charts, boxplots, histograms and line graphs for time series
data

4. [Data manipulation using dplyr](week4.html) - Filtering and modifying tabular
data, computing summary values, faceting with ggplot2

5. [Grouping and combining data](week5.html) - Advanced grouping and
summarization operations, joining data from different tables, customizing
ggplot2 plots

6. [Restructuring data for analysis](week6.html) - The concept of 'tidy data',
pivoting and separating operations, ggplot2 extras

7. **Capstone project** – putting it all together in a typical data analysis
including:

    * reading in a data set

    * handling missing values

    * selecting and filtering subsets of interest

    * creating plots

    * generating summary statistics

    * saving data transformed into a tidy format as a csv file for later analysis
